version: '3.8'

services:
  neo4j:
    build: 
      context: ./Neo4j
    container_name: graph-starz-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - graph-starz-network

  backend:
    build: 
      context: ./Backend
    container_name: graph-starz-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEO4J_URI=bolt://graph-starz-neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - graph-starz-network

networks:
  graph-starz-network:
    name: graph-starz-network
